services:
  db:
    image: postgres:14-alpine
    container_name: express_postgres
    restart: always
    environment:
      POSTGRES_USER: abc168
      POSTGRES_PASSWORD: abc168!!
      POSTGRES_DB: ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
